### ISSUE TITLE
希望能把同步帐户和同步密码加密呀

### ISSUE THREAD

**Issue by xavierzhao** [ivanchoo/TracWikiSync#1]
明文放在trac.ini太不负责了。

**Comment by ivanchoo** [comment]
当前密码已经是屏蔽的，但估计用户名也可同样处理。

不考虑加密处理，因为还得考虑加密算法和秘钥管理等等流程。

绝大多数人都是本定部署，密码加密多此一举。如真有需要，请fork并实现自己的配置存储。
